// @ts-check
/**
 * @module backend/services/inference
 *
 * Pure JavaScript MLP inference — no Python dependency.
 *
 * Architecture: 788 → Linear(256) → BN → ReLU → Linear(128) → BN → ReLU → Linear(2) → Softmax
 *
 * Loads pre-exported model weights from model_weights.json (generated by export_weights.py).
 * This eliminates the need for Python/PyTorch on the server entirely.
 */

import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { EventEmitter } from 'events';
import logger from '../utils/logger.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const NUM_PROPERTY_FEATURES = 20;
const BN_EPS = 1e-5;

// ============================================================
// Matrix math helpers
// ============================================================

/**
 * Matrix-vector multiply: y = W * x + b
 * W is [outDim, inDim], x is [inDim], b is [outDim]
 * @param {number[][]} W
 * @param {number[]} x
 * @param {number[]} b
 * @returns {number[]}
 */
function linear(W, x, b) {
  const out = new Array(W.length);
  for (let i = 0; i < W.length; i++) {
    let sum = b[i];
    const row = W[i];
    for (let j = 0; j < row.length; j++) {
      sum += row[j] * x[j];
    }
    out[i] = sum;
  }
  return out;
}

/**
 * BatchNorm1d in eval mode: y = gamma * (x - mean) / sqrt(var + eps) + beta
 * @param {number[]} x
 * @param {number[]} gamma - weight
 * @param {number[]} beta - bias
 * @param {number[]} runMean
 * @param {number[]} runVar
 * @returns {number[]}
 */
function batchNorm(x, gamma, beta, runMean, runVar) {
  const out = new Array(x.length);
  for (let i = 0; i < x.length; i++) {
    const normalized = (x[i] - runMean[i]) / Math.sqrt(runVar[i] + BN_EPS);
    out[i] = gamma[i] * normalized + beta[i];
  }
  return out;
}

/** ReLU activation (in-place safe) */
function relu(x) {
  const out = new Array(x.length);
  for (let i = 0; i < x.length; i++) {
    out[i] = x[i] > 0 ? x[i] : 0;
  }
  return out;
}

/** Softmax */
function softmax(x) {
  const maxVal = Math.max(...x);
  const exps = x.map((v) => Math.exp(v - maxVal));
  const sum = exps.reduce((a, b) => a + b, 0);
  return exps.map((v) => v / sum);
}

// ============================================================
// Inference Service
// ============================================================

class InferenceService extends EventEmitter {
  constructor() {
    super();
    this._isReady = false;
    this.weights = null;
  }

  /**
   * Load model weights from JSON file.
   * @returns {Promise<void>}
   */
  async start() {
    try {
      // Look for model_weights.json relative to project root
      const weightsPath = resolve(__dirname, '..', '..', '..', 'inference', 'models', 'model_weights.json');
      logger.info({ path: weightsPath }, 'Loading JS model weights...');

      const raw = readFileSync(weightsPath, 'utf-8');
      this.weights = JSON.parse(raw);

      this._isReady = true;
      logger.info('✅ Pure JS inference engine ready (no Python needed)');
      this.emit('ready');
    } catch (err) {
      logger.error({ err }, 'Failed to load model weights');
      throw err;
    }
  }

  /**
   * Run MLP forward pass in pure JS.
   *
   * @param {number[]} features - 788-dim feature vector (or 20-dim if LaBSE disabled)
   * @param {boolean} [computeImportance=true]
   * @returns {Promise<import('./inference.service.js').InferenceResult>}
   */
  async predict(features, computeImportance = true) {
    if (!this._isReady || !this.weights) {
      throw new Error('Inference service not ready');
    }

    const startTime = performance.now();
    const w = this.weights;

    // Pad to 788 dims if only 20 features provided (LaBSE disabled)
    let input = features;
    if (input.length === NUM_PROPERTY_FEATURES) {
      input = [...input, ...new Array(768).fill(0)];
    }

    if (input.length !== 788) {
      return {
        predictedClass: -1,
        probabilities: [0, 0],
        featureImportance: [],
        inferenceTimeMs: 0,
        error: `Expected 788 or 20 features, got ${input.length}`,
      };
    }

    // Forward pass: layer1
    let x = linear(w['layer1.0.weight'], input, w['layer1.0.bias']);
    x = batchNorm(x, w['layer1.1.weight'], w['layer1.1.bias'], w['layer1.1.running_mean'], w['layer1.1.running_var']);
    x = relu(x);
    // (Dropout is no-op in eval mode)

    // Forward pass: layer2
    x = linear(w['layer2.0.weight'], x, w['layer2.0.bias']);
    x = batchNorm(x, w['layer2.1.weight'], w['layer2.1.bias'], w['layer2.1.running_mean'], w['layer2.1.running_var']);
    x = relu(x);

    // Forward pass: classifier
    const logits = linear(w['classifier.weight'], x, w['classifier.bias']);
    const probabilities = softmax(logits);
    const predictedClass = probabilities[1] > probabilities[0] ? 1 : 0;

    // Simple feature importance via weight magnitude (approximation)
    let featureImportance = [];
    if (computeImportance) {
      featureImportance = computeWeightImportance(w, input);
    }

    const inferenceTimeMs = Math.round((performance.now() - startTime) * 100) / 100;

    return {
      predictedClass,
      probabilities: [
        Math.round(probabilities[0] * 1e6) / 1e6,
        Math.round(probabilities[1] * 1e6) / 1e6,
      ],
      featureImportance,
      inferenceTimeMs,
    };
  }

  get ready() {
    return this._isReady;
  }

  async stop() {
    this._isReady = false;
    this.weights = null;
    logger.info('Inference service stopped');
  }
}

/**
 * Approximate feature importance using first-layer weight magnitudes.
 * For each of the 20 property features, sum the absolute weights
 * connecting it to all hidden units, then normalize.
 *
 * @param {Object} w - Model weights
 * @param {number[]} input - Input features
 * @returns {number[]} 20 importance values summing to ~1
 */
function computeWeightImportance(w, input) {
  const layer1W = w['layer1.0.weight']; // [256, 788]
  const importance = new Array(NUM_PROPERTY_FEATURES).fill(0);

  for (let feat = 0; feat < NUM_PROPERTY_FEATURES; feat++) {
    let sum = 0;
    for (let neuron = 0; neuron < layer1W.length; neuron++) {
      sum += Math.abs(layer1W[neuron][feat]) * Math.abs(input[feat]);
    }
    importance[feat] = sum;
  }

  // Normalize
  const total = importance.reduce((a, b) => a + b, 0);
  if (total > 0) {
    for (let i = 0; i < importance.length; i++) {
      importance[i] = Math.round((importance[i] / total) * 1e6) / 1e6;
    }
  }

  return importance;
}

/** Singleton inference service instance. */
export const inferenceService = new InferenceService();
