"""
Feature normalization utilities for MGTAB Detector.

Applies the exact same transformations used during training:
1. Boolean features: pass through (already 0/1)
2. Count features (heavy right-skew): log1p transform, then MinMax
3. Other numeric features: MinMax normalization

The normalization stats (min, max per feature) are loaded from
`normalization_stats.json`, which is generated by `train_mlp_v1.py`.
"""

import json
import math
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

# Features in the exact order they appear in the 788-dim vector (first 20)
PROPERTY_FEATURE_NAMES = [
    "profile_use_background_image",
    "default_profile",
    "verified",
    "followers_count",
    "default_profile_image",
    "listed_count",
    "statuses_count",
    "friends_count",
    "geo_enabled",
    "favourites_count",
    "created_at",
    "screen_name_length",
    "name_length",
    "description_length",
    "followers_friends_ratio",
    "default_profile_background_color",
    "default_profile_sidebar_fill_color",
    "default_profile_sidebar_border_color",
    "has_url",
    "profile_background_image_url",
]

# Features requiring log1p before MinMax
LOG_TRANSFORM_FEATURES = {
    "followers_count",
    "listed_count",
    "statuses_count",
    "friends_count",
    "favourites_count",
    "followers_friends_ratio",
}

# Boolean features — no normalization needed
BOOLEAN_FEATURES = {
    "profile_use_background_image",
    "default_profile",
    "verified",
    "default_profile_image",
    "geo_enabled",
    "default_profile_background_color",
    "default_profile_sidebar_fill_color",
    "default_profile_sidebar_border_color",
    "has_url",
    "profile_background_image_url",
}


def load_normalization_stats(stats_path: str) -> Dict:
    """Load precomputed normalization statistics from JSON."""
    with open(stats_path, "r") as f:
        return json.load(f)


def normalize_single_feature(
    value: float,
    feature_name: str,
    stats: Dict,
) -> float:
    """
    Normalize a single feature value using the same transforms as training.
    
    Args:
        value: Raw feature value.
        feature_name: Name of the feature (from PROPERTY_FEATURE_NAMES).
        stats: Normalization stats dict with min/max per feature.
        
    Returns:
        Normalized value in [0, 1].
    """
    # Boolean features are already binary
    if feature_name in BOOLEAN_FEATURES:
        return float(bool(value))

    # Apply log1p for count-based features
    if feature_name in LOG_TRANSFORM_FEATURES:
        value = math.log1p(value)

    # MinMax scaling
    feat_stats = stats["propertyFeatures"][feature_name]
    feat_min = feat_stats["min"]
    feat_max = feat_stats["max"]

    # Avoid division by zero for features with zero range
    if feat_max - feat_min < 1e-10:
        return 0.0

    normalized = (value - feat_min) / (feat_max - feat_min)
    # Clamp to [0, 1] for values outside training range
    return max(0.0, min(1.0, normalized))


def normalize_property_features(
    raw_features: Dict[str, float],
    stats: Dict,
) -> List[float]:
    """
    Normalize all 20 property features into a list in the correct order.
    
    Args:
        raw_features: Dict mapping feature names to raw values.
        stats: Normalization stats from training.
        
    Returns:
        List of 20 normalized values in PROPERTY_FEATURE_NAMES order.
    """
    normalized = []
    for name in PROPERTY_FEATURE_NAMES:
        raw_value = raw_features.get(name, 0.0)
        norm_value = normalize_single_feature(raw_value, name, stats)
        normalized.append(norm_value)
    return normalized


def build_feature_vector(
    property_features: List[float],
    tweet_embedding: Optional[List[float]] = None,
    embedding_dim: int = 768,
) -> List[float]:
    """
    Build the complete 788-dim feature vector.
    
    Args:
        property_features: 20 normalized property features.
        tweet_embedding: 768-dim LaBSE embedding (or None for zero vector).
        embedding_dim: Dimension of tweet embedding (default 768).
        
    Returns:
        Complete 788-dim feature vector.
    """
    if tweet_embedding is None:
        tweet_embedding = [0.0] * embedding_dim

    if len(tweet_embedding) != embedding_dim:
        raise ValueError(
            f"Expected embedding dim {embedding_dim}, got {len(tweet_embedding)}"
        )

    return property_features + tweet_embedding
